env:
  es2021: true
  node: true
extends:
  - eslint-config-snippets-book
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {}
